spring:
  application:
    name: Gerenciamento de Consentimentos
  data:
    mongodb:
      uri: mongodb://localhost:27017/consentdb
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 1.5
        auto-startup: true
        default-requeue-rejected: false

server:
  port: 8080

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.springframework.data.mongodb.repository.query: DEBUG
#    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver.operation: DEBUG
#    org.springframework.data.mongodb: DEBUG
#    org.mongodb.driver: DEBUG
#    com.dsena7: DEBUG
